### ISSUE TITLE
error with installation

### ISSUE THREAD

**Issue by scottchc** [cmvcamacho/continuous-integration-dashboard#2]
hello, i received this error running the install script, could you please advise?

Thanks,
Scott

C:\Users\CHASC05\Workspace\continuous-integration-dashboard-master-2\deploy>.\in
stall.bat local
Microsoft (R) Build Engine version 4.0.30319.34209
[Microsoft .NET Framework, version 4.0.30319.34209]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 10/27/2015 4:27:57 PM.
Project "C:\Users\CHASC05\Workspace\continuous-integration-dashboard-master-2\d
eploy\default.build" on node 1 (Install target(s)).
ManageDatabase:
  Copying file from "C:\Users\CHASC05\Workspace\continuous-integration-dashboar
  d-master-2\deploy\scripts\bootstrap.sql" to "C:\Users\CHASC05\Workspace\conti
  nuous-integration-dashboard-master-2\deploy\scripts\bootstrap_copy.sql".
  Going to replace #{ServiceUser} using NT AUTHORITY\LOCAL SERVICE
  Updating File "C:\Users\CHASC05\Workspace\continuous-integration-dashboard-ma
  ster-2\deploy\scripts\bootstrap_copy.sql".
  Going to replace #{DatabaseName} using CIDashboard
  Updating File "C:\Users\CHASC05\Workspace\continuous-integration-dashboard-ma
  ster-2\deploy\scripts\bootstrap_copy.sql".
  .\Tools\SqlCmd\SQLCMD.EXE -b -S CHASC05-W7\SQLEXPRESS -i "C:\Users\CHASC05\Wo
  rkspace\continuous-integration-dashboard-master-2\deploy\scripts\bootstrap_co
  py.sql"
  Changed database context to 'CIDashboard'.
  Deleting file "C:\Users\CHASC05\Workspace\continuous-integration-dashboard-ma
  ster-2\deploy\scripts\bootstrap_copy.sql".
C:\Users\CHASC05\Workspace\continuous-integration-dashboard-master-2\deploy\def
ault.build(64,3): **error MSB4062: The "MSBuild.ExtensionPack.Computer.HostsFile"
 task could not be loaded from the assembly C:\Users\CHASC05\Workspace\continuo
us-integration-dashboard-master-2\deploy\Tools\MSBuild Extension Pack 4.0.4.0 B
inaries\MSBuild.ExtensionPack.dll. Could not load file or assembly 'Ionic.Zip,
Version=1.9.1.8, Culture=neutral, PublicKeyToken=edbe51ad942a3f5c' or one of it
s dependencies. The system cannot find the file specified.** Confirm that the <Us
ingTask> declaration is correct, that the assembly and all its dependencies are
 available, and that the task contains a public class that implements Microsoft
.Build.Framework.ITask.
Done Building Project "C:\Users\CHASC05\Workspace\continuous-integration-dashbo
ard-master-2\deploy\default.build" (Install target(s)) -- FAILED.

Build FAILED.

"C:\Users\CHASC05\Workspace\continuous-integration-dashboard-master-2\deploy\de
fault.build" (Install target) (1) ->
(ManageHosts target) ->
  C:\Users\CHASC05\Workspace\continuous-integration-dashboard-master-2\deploy\d
efault.build(64,3): error MSB4062: The "MSBuild.ExtensionPack.Computer.HostsFil
e" task could not be loaded from the assembly C:\Users\CHASC05\Workspace\contin
uous-integration-dashboard-master-2\deploy\Tools\MSBuild Extension Pack 4.0.4.0
 Binaries\MSBuild.ExtensionPack.dll. Could not load file or assembly 'Ionic.Zip
, Version=1.9.1.8, Culture=neutral, PublicKeyToken=edbe51ad942a3f5c' or one of
its dependencies. The system cannot find the file specified. Confirm that the <
UsingTask> declaration is correct, that the assembly and all its dependencies a
re available, and that the task contains a public class that implements Microso
ft.Build.Framework.ITask.

```
0 Warning(s)
1 Error(s)
```

Time Elapsed 00:00:00.24

**Comment by cmvcamacho** [comment]
Hi Scott

I've noticed that some binaries for the MSBuild Extension Pack 4.0.4.0 were missing, I've committed them.

Please give it a try.

Thanks
Carlos Camacho

**Comment by brigs** [comment]
Hi.

Decided to give your project a try today :) It seems it's still missing some msbuild binaries. I compiled and restored all the nuget packages. Then I ran the deployscript:

```
Microsoft (R) Build Engine version 4.6.1055.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 07.12.2015 13:47:39.
Project "C:\g\continuous-integration-dashboard\deploy\default.build" on node 1 (Install target(s)).
ManageDatabase:
  Copying file from "C:\g\continuous-integration-dashboard\deploy\scripts\bootstrap.sql" to "C:\g\continuous-integration-dashboard\deploy\scripts\bootstrap_copy.sql".
  Going to replace #{ServiceUser} using NT AUTHORITY\LOCAL SERVICE
C:\g\continuous-integration-dashboard\deploy\default.build(51,3): error MSB4062: The "MSBuild.Community.Tasks.FileUpdate" task could not be loaded from the assembly C:\g\continuous-integration-dashboard\deploy\Tools\MSBuildCommunityTasks\M SBuild.Community.Tasks.dll. Could not load file or assembly 'file:///C:\g\continuous-integration-dashboard\deploy\Tools\MSBuildCommunityTasks\MSBuild.Community.Tasks.dll' or one of its dependencies. The system cannot find the file specifie d. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
Done Building Project "C:\g\continuous-integration-dashboard\deploy\default.build" (Install target(s)) -- FAILED.


Build FAILED.

"C:\g\continuous-integration-dashboard\deploy\default.build" (Install target) (1) ->
(ManageDatabase target) ->
  C:\g\continuous-integration-dashboard\deploy\default.build(51,3): error MSB4062: The "MSBuild.Community.Tasks.FileUpdate" task could not be loaded from the assembly C:\g\continuous-integration-dashboard\deploy\Tools\MSBuildCommunityTasks \MSBuild.Community.Tasks.dll. Could not load file or assembly 'file:///C:\g\continuous-integration-dashboard\deploy\Tools\MSBuildCommunityTasks\MSBuild.Community.Tasks.dll' or one of its dependencies. The system cannot find the file specif ied. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.04
```

**Comment by netflash** [comment]
Same story here. 
@cmvcamacho could you please help with the installation ?
